### ISSUE TITLE
Consider removing sonarjs/no-duplicate-string

### ISSUE THREAD

**Issue by mutantcornholio** [paritytech/opstooling-js-style#12]
In my career, I don't really remember seeing cases of "magic strings" problems, as they are usually perceived/depicted
Like, something that you'll have to change in all those places.  

Usually, programmers are wary of this, even interns.  

This rule, however, already bugged me a couple of times on cases like in the screenshot. 
Extracting sting literal into a variable just going to mess it up. And there's no way somebody will just change it in one place. Like.. why?  

![Screen Shot 2022-07-01 at 18 03 13](https://user-images.githubusercontent.com/588262/176930892-f246067e-e4d6-4b98-b146-703fb9773d6e.png)

Do you feel like we're better with this rule, or without it?

**Comment by joao-paulo-parity** [comment]
This is actually a good example where you can do `...options` in the cases where `param: "some param"` is repeated. And in case you want to add more fields to the options they can just be added the object directly without causing a needless diff changes throughout the entire file, which would make future PRs noisier during review.

> Like, something that you'll have to change in all those places

One of the reasons for not having code repetition is precisely to avoid this kind of situation where you have to manually change a value everywhere

> Extracting sting literal into a variable just going to mess it up

Needs elaboration

> In my career, I don't really remember seeing cases of "magic strings" problems

1. Avoiding error-prone manual repetition isn't the only reason for abstracting repeated code. I can mention two other benefits off the top of my head: it makes changing the value easier (change 1 place vs many) and that leads to smaller diff sizes.
2. Just because something hasn't happened historically doesn't mean that it won't happen in the future

All that being said those are test files, so it's _less bad_ to disable that rule for test files specifically, although there are cases where it's useful, like this one.

> And there's no way somebody will just change it in one place. Usually, programmers are wary of this, even interns.

Loosening some code analysis aspect on the basis of "we'll trust that developers will pay attention to it" isn't something I can generally agree with

**Comment by joao-paulo-parity** [comment]
As an aside, this is an example of why #9 might be useful. If a core principle of the ruleset would be to "avoid code repetition" then a decision could be made around that idea instead of arguing based on personal biases. I highly value abstractions to avoid manual code repetition (as shown in https://github.com/paritytech/gitspiegel/pull/96#discussion_r908258587 and many other comments throughout that gitspiegel PR) _even_ at the cost of complexity - not like I think this sort of transformation increases complexity or decreases readability for me in any case, but it's a tradeoff I'm willing to make for the cases that need it. Another example would be if opstooling-js-style had a core principle of "syntax consistency" because in that case we'd for example prefer `"always"` for https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/return-await.md as _always_ using return leads to more consistent syntax usage.

That being said I don't think that resuming the discussion of https://github.com/paritytech/opstooling-js-style/issues/9 deserves to be prioritized at the moment given that we have more important things to do.

cc @mordamax

**Comment by mutantcornholio** [comment]
I actually find your position of treating code repetition as absolute evil too excessive.  
Consider [this script](https://github.com/paritytech/gitspiegel/blob/aa32e9e294ecfde3a59b09178782206576515fc3/scripts/generateDockerfile), the only purpose of which seems to be not to repeat `FROM node:16.14-alpine` line.  
Or [this case](https://github.com/paritytech/command-bot/pull/57/files/7d6e3a64793472857de7af82e10a4dfc89896374..0284c22d7061a91553f7fb92d179b5ff95659018#r869046626) which we've discussed earlier.  

And now suggesting to nominate "avoid code repetition" as a dogmatic core principle of codestyle? Not "code should be easy to read and understand", not something like "explicit is better than implicit" (both of them will be conflicting with your suggestion).  

Why is it so important?

> One of the reasons for not having code repetition is precisely to avoid this kind of situation where you have to manually change a value everywhere

So, I'm making a point that never in my career did I have such issues, and you're saying that this rule helps to avoid those? I never used this rule, and still those problems didn't arise.  

> 1. Avoiding error-prone manual repetition isn't the only reason for abstracting repeated code. I can mention two other benefits off the top of my head: it makes changing the value easier (change 1 place vs many) and that leads to smaller diff sizes.

You're literally writing more code than you save. That's the opposite of smaller diff sizes.  

> 2. Just because something hasn't happened historically doesn't mean that it won't happen in the future

First, it just shows a really low probability of an event, and I say it's far too low to force us complying to a rule that's designed to fight it.  
Second, what I said, was that programmers are wary of it. It's a knowledge that's in us from the very first programming book that we read. If somebody's not aware of this, do you think it'll pass the review? If this will happen for the first time of my life, well, okay, I don't think that it would be the worst bug I've seen.  

> Loosening some code analysis aspect on the basis of "we'll trust that developers will pay attention to it" isn't something I can generally agree with

Code analysis is also all about signal/noise. This rule saved me from zero problems. It just generated noise.

**Comment by mutantcornholio** [comment]
Just to be clear: I'm not saying that code repetition is good. I'm avoiding code repetition everywhere where the code will be smaller and easier to read afterwards.  
And I also (like everybody else) tend to "magic strings" problem.  
But inventing complex ways to avoid code repetition, where it poses that little danger, seems like a cargo-cult to me.

**Comment by joao-paulo-parity** [comment]
> And now suggesting to nominate "avoid code repetition" as a dogmatic core principle of codestyle

That is not being suggested in that comment. It says "_**If**_ a core principle of the ruleset _**would be**_ to "avoid code repetition"" and that's merely for illustration purposes. It doesn't make sense to extrapolate the mention of a possibility into an actual proposal, even more so in that case where it's only being used as an example. Should I also have added "Hypothetically" at the start of that sentence for a third redundant conditional, just to get the point across?

> So, I'm making a point that never in my career did I have such issues, and you're saying that this rule helps to avoid those? I never used this rule, and still those problems didn't arise.

I've seen it happen before where a value wasn't properly updated in some places and it would've been easier to do if it was tied to a variable. Having to do project-wide manual search-and-replace is more error-prone, and yes, problems happened because of this. Imagine the following situation

```js
const bikeModel = "XMZ48"
const bikeSerialNumber = "XMZ48-834"
```

vs

```js
export const bikeModel = "XMZ48"
export const bikeSerialNumber = `${bikeModel}-834`
```

Two obvious benefits of the second approach

- If I want to change to change the bike model to `XMC20` I only have to change one line, compared to the first which would be double

```diff
-export const bikeModel = "XMZ48"
+export const bikeModel = "XCM20"
```

- I want to refactor/rename `bikeModel` to something else I can use IDE assistance for that instead of having to manually check each occurrence of `XMZ48` throughout the project.

I've seen this problem come up before, but even if I hadn't, to me it's clearly better to go for the least error-prone approach, that is: put repeated code in a language construct so that it can reused, rather than forcing developers to manually verify and ensure consistency by themselves. Since I'm in a team setting I have to think about what's least error-prone for the team as a whole first, myself second.

> You're literally writing more code than you save. That's the opposite of smaller diff sizes.

I mentioned situations about _**changing**_ the value. Compare

```js
const options = { param: 'some param' };
expect(res).toEqual({ status: 'success', ...options });
expect(res2).toEqual({ status: 'failure', ...options });
```

vs

```js
expect(res).toEqual({ status: 'success', param: "some param" });
expect(res2).toEqual({ status: 'failure', param: "some param" });
```

If I want to change `param` to "foobar" in the first option

```diff
-const options = { param: 'some param' };
+const options = { param: 'foobar' };
```

For the second option

```diff
-expect(res).toEqual({ status: 'success', param: 'some param'  });
+expect(res).toEqual({ status: 'success', param: "foobar" });
-expect(res2).toEqual({ status: 'failure', param: 'some param' });
+expect(res2).toEqual({ status: 'failure', param: "some param" });
```

Now imagine if I wanted to add a new field to `options`. In the first case that's again a single line change, where in the second case it's a `N` line change where I'll have to manually copy-and-paste the new value everywhere and maintain their consistency after.

Regardless of "How often are you going to change the value?" and "How big of a problem is it if you mess up?", for me it intuitively makes sense to go for the pattern that leads less repetition as that's less error-prone, requires less manual work to maintain, and produces smaller diffs on changes; all of this is valuable for **team collaboration** in a codebase. If I'm working on something alone I might choose to do something different, but that's entirely beside the point.

> But inventing complex ways to avoid code repetition, where it poses that little danger, seems like a cargo-cult to me.

I really cannot fathom why you say that `...options` is "more complex" than manually repeating `param: "some param"` throughout the whole file. "More complex" for who, and how? Doesn't manually copy-and-pasting the same value everywhere also make maintenance "more complex"? What exactly is the problem there? Is it just that you dislike having to create variables for repeated code? As a professional developer it's natural to consider what's better for the code **in a team setting**. To me that means going for the least error-prone way of writing code rather than pleasing someone's personal preferences. Vouching for an individual's preferences on the basis of "well it's not a big problem if it goes bad anyways, so let's keep it how X person prefers" is definitely not how I approach work and that sort of thinking is entirely unconvincing to me.

Also why does "cargo cult" even come into play for this discussion? Someone's opinion and way of thinking shouldn't be belittled like that in a professional setting. Here's how you could've phrased:

> But inventing complex ways to avoid code repetition, where it poses that little danger, seems inefficient | wasteful | excessive | [...].

There are plenty of ways for you to use less confrontational/offensive/condescending language when making a statement like that, but time and time again the word choice is severely lacking in this regard.

To your point: does that case "pose a little danger"? Yes, even more so because it's only for tests and I even mentioned in https://github.com/paritytech/opstooling-js-style/issues/12#issuecomment-1181553627 that it's less bad to have some repetition for test files specifically, but this very scenario shows why that rule might be relevant for tests as well. Regardless of personal preferences, I truly believe that code repetition is undesirable for team collaboration.

The "there's a low probability of things going bad, therefore it's fine" kind of reasoning is unconvincing to me as I've openly stated in https://github.com/paritytech/opstooling/issues/125#issuecomment-1175188252 and probably some other places as well, but we end up running into that sort of argument every time and wasting time on it. Accepting that the worst-case scenarios won't happen is unreasonable to me, so I suggest we drive the discussion around something else.

> I actually find your position of treating code repetition as absolute evil too excessive.

In https://github.com/paritytech/gitspiegel/pull/88#discussion_r901402769 for instance I've noticed that only one field was being repeated - which don't get me wrong, I think it's bad - but since it was only one field repeated in a few places all close to each other, I didn't think it's too bad, so I didn't insist on that point.

On the other hand, for https://gitlab.parity.io/parity/opstooling/vanity-service/-/blob/817ce9b5f97426a4e420c33781ede9428fcafff8/spec/utils/preventGithubRateLimit.spec.js the copy-and-pasting of `param: 'some param'` is definitely too much since if I change `options` I'll also have to manually updated everywhere that `options` is (implictly) used. There's a coupling between those parts of the code but it's not apparent from reading it. Alternatively, if there's repetition but the repetition isn't coupled, like in https://github.com/paritytech/gitspiegel/blob/78049c6c56ed6c314725ab516eb31e05ba4953ea/src/metrics.ts#L3, I'm less likely to be bothered about it.

You using words such as "absolute evil" and "cargo cult" like I'm mindlessly inflexible about this is insensitive to say the least. Yes I have strong opinions about what's better for team collaboration, but please refrain from being patronizing in implying that I'm blinded by some idea just because I don't agree with you.

**Comment by mutantcornholio** [comment]
Sorry if anything here offended you

**Comment by joao-paulo-parity** [comment]
> Sorry if anything here offended you

I'm bothered by the language mainly because I think the word choice and the tone aren't a good fit for a professional discussion, but it's not hurting me anyhow. It's all good.

---

As a final thought, I'd like to add something that came up while I was mulling over this discussion. I feel like you think that my motivation for avoiding code repetition is to reduce the amount of code. Truly, I don't care about code size at all. My main reasons for endorsing the reduction of manual code repetition are:

- Copy-and-paste can make the code harder to maintain in some cases because they incur implicit, hard-to-intuit coupling throughout different parts of the code. e.g. if I change https://github.com/paritytech/gitspiegel/blob/78049c6c56ed6c314725ab516eb31e05ba4953ea/src/health.ts#L70 I have to also **remember** to change https://github.com/paritytech/gitspiegel/blob/78049c6c56ed6c314725ab516eb31e05ba4953ea/src/metrics.ts#L37; and yes, it's "not a big deal" in case those places end up desynchronized, but I already explained thoroughly throughout https://github.com/paritytech/gitspiegel/pull/96 that I think this kind of thing is important; we have the means to avoid that problem, so let's put them to use.
- When values are manually copy-and-pasted throughout the code, any future changes to it incur mechanical adjustments and diffs to `N` usage sites rather than a single place, the definition site.
- Copy-and-paste is error-prone. In some cases the error is simple to fix and detect or it doesn't have a huge impact, but I think it's better to go for an approach which doesn't allow for those problems to come up in the first place since the code becomes more maintainable that way.

For the scenario you present doing this is already facilitated since the manual repetitions of `params: 'some param'` can be trivially changed to `...options` and doing that doesn't require a lot of effort, nor it would make the code anyhow worse, unless I'm missing something.

Also it's really weird to me that you go through the trouble of disabling a linting rule and incite a huge discussion on it on the basis of a personal preference. I'd not object at all if the reasoning for disabling https://gitlab.parity.io/parity/opstooling/vanity-service/-/merge_requests/48/diffs#3cd7e332e0fc355c35ed89c85edd72cf52642868_0_9 was

```js
/*
  Disabling this rule because I don't want to refactor the code being brought over
  from the old vanity-service right now.
  TODO: deal with it later.
*/
```

But instead it is

```js
// Extracting "some param" into a variable will just make it harder to read
```

And initially you didn't see a problem at all with trampling over a linting rule on that basis, so the TODO was only added because I objected to it in https://gitlab.parity.io/parity/opstooling/vanity-service/-/merge_requests/48/diffs#note_158081. I don't know where that kind of entitlement of "I think Y makes the code worse, so I'm going to disable it because I want to" comes from, but it's not acceptable in that case. We're still discussing the rule and it _could_ be disabled later, but it's still active right now and should be respected except if the file is somehow special e.g. https://github.com/paritytech/gitspiegel/blob/78049c6c56ed6c314725ab516eb31e05ba4953ea/src/metrics.ts#L4. For me it would be irresponsible to approve that sort of conduct on the basis of "well it's fine if X person wants it to be that way, I don't want to object on this because it would be a bother, so I'll just ignore it". One of the main reasons for having a ruleset in the first place is for us to avoid spending lots of effort discussing and tweaking the code based on subjective preferences, so that justification really invites unwarranted commotion. A rule change should be proposed, acknowledged, reviewed, accepted, merged to master, and only then we can apply it throughout the code; there are no grounds for them to be arbitrarily disabled whenever someone feels like it. Do we want to invite that sort of discussion in the future? I don't want to, personally.

**Comment by mutantcornholio** [comment]
Dude, chill

**Comment by mutantcornholio** [comment]
I heard you
