### ISSUE TITLE
Define core principles and ideas for opstooling-js-style

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/opstooling-js-style#9]
The set of linting rules shouldn't be based on personal preferences, which is subject to change as the OpsTooling team members changes throughout time, but rather it should be based on a set of consensually agreed principles. That would imply rules are implemented on the basis of those principles rather than stylistic/aesthetic preferences of OpsTooling members.

Examples of principles/notions:

- Syntax consistency
- Ease of refactoring
- etc...

If, in the future, the OpsTooling team would change its leadership/memberships and decide to go in some other direction, they would be encouraged to do so by changing the principles rather than editing arbitrary rules it to their liking.

After those principles are established we should revisit the current rules.

**Comment by mutantcornholio** [comment]
I kinda feel like establishing "core principles" for codestyle definition is bit of an overkill for a team of three.
If we want to invest that kind of time on codestyle, shouldn't we aim at least on company level?

**Comment by joao-paulo-parity** [comment]
> establishing "core principles" for codestyle definition is bit of an overkill

What's being proposed here is a solution to the "everyone's personal preference" problem. Whether it's "overkill" or not (I don't think it is) does not take away from the purpose of this ticket which is to find a solution to the problem raised or decide on not dealing with the problem. If you think "it's not a problem" or "it's not worth expending time on this problem" then it'll be more productive to state that explicitly, because "it is overkill" does not constitute a reason to not deal with the problem. Ultimately we should decide on whether this will be done or not despite being "overkill" (if it is) or postpone the decision for later. i.e. meandering about the cost of implementation for this proposal isn't what's relevant at this point, it's whether or not it's worth it to follow this path **now or in the future**.

And why is "everyone's personal preference" a problem? Because that'll lead to unnecessary refactors as team members (and therefore their personal preferences) changes. Also it's a waste of time to be constantly discussing and changing arbitrary rules, then reapplying them everywhere.

> for a team of three

I don't know why that matters. OpsTooling members (who own of this repository, not whoever's managing the team sizes) don't have a definite say on team sizes, nor we have a explicit statement on "the current amount of members will stay as it is in the long term" to back that kind of notion.

> If we want to invest that kind of time on codestyle

Nowhere I'm suggesting to prioritize this issue right now. It can be done when there's time for it. It's even labeled as `needs planning`.

>  shouldn't we aim at least on company level?

1. If someone is interested in applying the rules on a company level they can simply extend the rule and create their own repository. It shouldn't influence what we're doing here.
2. Applying the rules company-wide is not directly relevant to the problem raised by this ticket.
3. Personally I don't think it "applying this repository on a company level" gives more or less justification as for dealing or not dealing with the problem.

**Comment by mutantcornholio** [comment]
I'd like to think about it in terms of impact/effort ratio.  
I went through a process like this before, and the effort was **considerable**.  
And I really question the impact here.

> Personally I don't think it "applying this repository on a company level" gives more or less justification as for dealing or not dealing with the problem

Using the same terms, impact for company-level codestyle guidelines is definitely more tangible, comparing to codestyle guidelines for one team.

> because "it is overkill" does not constitute a reason to not deal with the problem.

I think it does. We should always pick our battles and some shouldn't be picked.  
To me, this problem seems minor, and the means required to deal with it, aren't comparable.  

> Also it's a waste of time to be constantly discussing and changing arbitrary rules, then reapplying them everywhere.

Let's apply the same logic for all the changes. If majority thinks that reapplying rules brings more positive impact than the effort wasted, why not do it?  

>> If we want to invest that kind of time on codestyle

> Nowhere I'm suggesting to prioritize this issue right now. It can be done when there's time for it.

It's still an investment of considerable amount of time, and I still do question whether it should be tackled at all.

**Comment by mordamax** [comment]
my 5 cents - Ideas and principles are good, as long as they make team stronger, routines smoother and what we produce more reliable. In other words - what are the main goals?
If that leads into irritative (rather than productive) discussions, I'd rather just keep using what we have right now and adjust, or do every project with its own style-guide, if that will help everyone to move forward instead of having long discussions whether we wrap the line or not.

**Comment by mutantcornholio** [comment]
I do believe that we are able to come up, discuss and refine the principles for codestyle.  

I just don't think it's that important / impactful.  
I've always treated codestyle as something like a way of organising a shared workplace. If you don't like where your pliers or soldering iron are located, or how the cable routing is done, you raise a question to move it/redo it. You don't have to have guiding principles about it.  

If we were to do it for a thousands of workplaces, having some guiding principles and maybe even metrics to support the chosen approach would be a good start, but should we do it for a small team like ours?

**Comment by mordamax** [comment]
I think it's already defined in code, anyone could propose some changes via pull request, so closing
